git rm Cell.class
git rm Client.class
git rm ClientEvent.class
git rm ClientListener.class
git rm DirectedPoint.class
git rm Direction.class
git rm EchoPacket.class
git rm GUIClient.class
git rm LocalClient.class
git rm Maze.class
git rm MazeImpl$1.class
git rm MazeImpl$CellImpl.class
git rm MazeImpl.class
git rm MazeListener.class
git rm Mazewar.class
git rm MazewarClient.class
git rm OverheadMazePanel.class
git rm Point.class
git rm Projectile.class
git rm RemoteClient.class
git rm RobotClient.class
git rm ScoreTableModel$ScoreWrapper.class
git rm ScoreTableModel.class
git rm SortedMultiSet.class
